color_black_pearl = '#08162C'
color_picton_blue = '#32AEDF'
color_dusty_gray = '#AD99A6'
color_fun_blue = '#1466AB'
color_blue = '#53BED6'
# color_light_gray = '#90A4AE'
color_light_gray = '#B0BEC5'
color_gray_extralight = '#F8F9FB'
# color_light_gray = '#CFD8DC'
color_white = '#ffffff'

typography_size_md = '16px'
typography_line_height_md = '24px'
typography_size_lg = '24px'
typography_line_height_lg = '32px'
typography_size_xl = '32px'
typography_line_height_xl = '40px'
typography_size_xxl = '48px'
typography_size_xxxl = '64px'
typography_line_height_xxxl = '1'

border_radius_xl = '16px'

styles_components_filepath = f'styles/tmp/components.css'
styles_blocks_filepath = f'styles/tmp/blocks.css'