data = [
    {
        "sector_name_eng": "Water",
        "sector_name": "Acqua",
        "sector_name_simple": "Acqua",
        "sector_name_normalize": "acqua",
        "sector_slug": "acqua",
        "sector_parent_name_normalize": None,
        "description": "Gestione, trattamento, distribuzione e utilizzo delle risorse idriche",
    },
    {
        "sector_name_eng": "Food & Beverage",
        "sector_name": "Alimentare",
        "sector_name_simple": "Alimentare",
        "sector_name_normalize": "alimentare",
        "sector_slug": "alimentare",
        "sector_parent_name_normalize": None,
        "description": "Produzione, trasformazione, distribuzione e consumo di alimenti e bevande",
    },
    {
        "sector_name_eng": "Agriculture",
        "sector_name": "Agricoltura",
        "sector_name_simple": "Agricoltura",
        "sector_name_normalize": "agricoltura",
        "sector_slug": "agricoltura",
        "sector_parent_name_normalize": None,
        "description": "Coltivazione, produzione agricola e gestione delle attività rurali",
    },
    {
        "sector_name_eng": "Healthcare",
        "sector_name": "Sanità",
        "sector_name_simple": "Sanità",
        "sector_name_normalize": "sanita",
        "sector_slug": "sanita",
        "sector_parent_name_normalize": None,
        "description": "Servizi sanitari, assistenza medica, strutture e tecnologie per la salute",
    },
    {
        "sector_name_eng": "Hospitality",
        "sector_name": "Ospitalità",
        "sector_name_simple": "Ospitalità",
        "sector_name_normalize": "ospitalita",
        "sector_slug": "ospitalita",
        "sector_parent_name_normalize": None,
        "description": "Servizi di ospitalità, ricettività, ristorazione e accoglienza degli ospiti",
    },
    {
        "sector_name_eng": "Buildings",
        "sector_name": "Edilizia",
        "sector_name_simple": "Edilizia",
        "sector_name_normalize": "edilizia",
        "sector_slug": "edilizia",
        "sector_parent_name_normalize": None,
        "description": "Progettazione, costruzione, gestione e manutenzione degli edifici",
    },
    {
        "sector_name_eng": "Manufacturing",
        "sector_name": "Manifatturiero",
        "sector_name_simple": "Manifatturiero",
        "sector_name_normalize": "manifatturiero",
        "sector_slug": "manifatturiero",
        "sector_parent_name_normalize": None,
        "description": "Produzione e trasformazione industriale di beni, componenti e prodotti",
    },
    {
        "sector_name_eng": "Energy",
        "sector_name": "Energia",
        "sector_name_simple": "Energia",
        "sector_name_normalize": "energia",
        "sector_slug": "energia",
        "sector_parent_name_normalize": None,
        "description": "Produzione, distribuzione, gestione e consumo di energia",
    },
    {
        "sector_name_eng": "Environment",
        "sector_name": "Ambiente",
        "sector_name_simple": "Ambiente",
        "sector_name_normalize": "ambiente",
        "sector_slug": "ambiente",
        "sector_parent_name_normalize": None,
        "description": "Tutela ambientale, gestione delle risorse naturali, rifiuti e sostenibilità",
    },
    {
        "sector_name_eng": "Transportation",
        "sector_name": "Trasporti",
        "sector_name_simple": "Trasporti",
        "sector_name_normalize": "trasporti",
        "sector_slug": "trasporti",
        "sector_parent_name_normalize": None,
        "description": "Trasporto e movimentazione di persone e merci attraverso infrastrutture e mezzi di trasporto",
    },
    {
        "sector_name_eng": "Residential",
        "sector_name": "Residenziale",
        "sector_name_simple": "Residenziale",
        "sector_name_normalize": "residenziale",
        "sector_slug": "residenziale",
        "sector_parent_name_normalize": None,
        "description": "Edifici, abitazioni e servizi destinati all'uso residenziale",
    },
    {
        "sector_name_eng": "Research",
        "sector_name": "Ricerca",
        "sector_name_simple": "Ricerca",
        "sector_name_normalize": "ricerca",
        "sector_slug": "ricerca",
        "sector_parent_name_normalize": None,
        "description": "Attività di ricerca, sviluppo, sperimentazione e innovazione scientifica e tecnologica",
    },
]
