
data = [
    {
        "sector_name": "Agricoltura e Produzione Animale",
        "sector_name_simple": "Agricoltura e Produzione Animale",
        "sector_name_normalize": "agricoltura_e_produzione_animale",
        "sector_slug": "agricoltura-produzione-animale",
        "sector_parent_name_normalize": None,
        "description": "Colture, allevamento e produzione agricola",
    },
    {
        "sector_name": "Alimentare e Bevande",
        "sector_name_simple": "Alimentare e Bevande",
        "sector_name_normalize": "alimentare_e_bevande",
        "sector_slug": "alimentare-bevande",
        "sector_parent_name_normalize": None,
        "description": "Trasformazione alimentare, produzione di bevande e stoccaggio di alimenti",
    },
    {
        "sector_name": "Acqua e Acque Reflue",
        "sector_name_simple": "Acqua e Acque Reflue",
        "sector_name_normalize": "acqua_e_acque_reflue",
        "sector_slug": "acqua-acque-reflue",
        "sector_parent_name_normalize": None,
        "description": "Acqua potabile, acque reflue municipali, acque industriali e riutilizzo dell'acqua",
    },
    {
        "sector_name": "Acquacoltura e Pesca",
        "sector_name_simple": "Acquacoltura e Pesca",
        "sector_name_normalize": "acquacoltura_e_pesca",
        "sector_slug": "acquacoltura-pesca",
        "sector_parent_name_normalize": None,
        "description": "Pesci, molluschi, avannotterie e sistemi di acquacoltura",
    },
    {
        "sector_name": "Sanità e Scienze della Vita",
        "sector_name_simple": "Sanità e Scienze della Vita",
        "sector_name_normalize": "sanita_e_scienze_della_vita",
        "sector_slug": "sanita-scienze-vita",
        "sector_parent_name_normalize": None,
        "description": "Ospedali, cliniche, laboratori e aziende farmaceutiche e biotecnologiche",
    },
    {
        "sector_name": "Ospitalità e Tempo Libero",
        "sector_name_simple": "Ospitalità e Tempo Libero",
        "sector_name_normalize": "ospitalita_e_tempo_libero",
        "sector_slug": "ospitalita-tempo-libero",
        "sector_parent_name_normalize": None,
        "description": "Hotel, resort, piscine, spa e strutture per il tempo libero con utilizzo dell'acqua",
    },
    {
        "sector_name": "Strutture Commerciali e Istituzionali",
        "sector_name_simple": "Strutture Commerciali e Istituzionali",
        "sector_name_normalize": "strutture_commerciali_e_istituzionali",
        "sector_slug": "strutture-commerciali-istituzionali",
        "sector_parent_name_normalize": None,
        "description": "Uffici, scuole, negozi ed edifici pubblici e commerciali",
    },
    {
        "sector_name": "Produzione Industriale",
        "sector_name_simple": "Produzione Industriale",
        "sector_name_normalize": "produzione_industriale",
        "sector_slug": "produzione-industriale",
        "sector_parent_name_normalize": None,
        "description": "Produzione industriale generale e industrie di processo",
    },
    {
        "sector_name": "Cellulosa, Carta e Tessile",
        "sector_name_simple": "Cellulosa, Carta e Tessile",
        "sector_name_normalize": "cellulosa_carta_e_tessile",
        "sector_slug": "cellulosa-carta-tessile",
        "sector_parent_name_normalize": None,
        "description": "Produzione di cellulosa, carta, tessuti e fibre",
    },
    {
        "sector_name": "Ambiente e Bonifica",
        "sector_name_simple": "Ambiente e Bonifica",
        "sector_name_normalize": "ambiente_e_bonifica",
        "sector_slug": "ambiente-bonifica",
        "sector_parent_name_normalize": None,
        "description": "Suolo, aria, siti contaminati, trattamento degli odori e interventi di bonifica ambientale",
    },
    {
        "sector_name": "Residenziale e Domestico",
        "sector_name_simple": "Residenziale e Domestico",
        "sector_name_normalize": "residenziale_e_domestico",
        "sector_slug": "residenziale-domestico",
        "sector_parent_name_normalize": None,
        "description": "Abitazioni, appartamenti e applicazioni domestiche per il trattamento dell'acqua e dell'aria",
    },
    {
        "sector_name": "Ricerca, Laboratori e Applicazioni Specialistiche",
        "sector_name_simple": "Ricerca, Laboratori e Applicazioni Specialistiche",
        "sector_name_normalize": "ricerca_laboratori_e_applicazioni_specialistiche",
        "sector_slug": "ricerca-laboratori-applicazioni-specialistiche",
        "sector_parent_name_normalize": None,
        "description": "Strutture di ricerca e sistemi di ozono per applicazioni specialistiche",
    },

    {
        "sector_name": "Lattiero-caseario",
        "sector_name_simple": "Lattiero-caseario",
        "sector_name_normalize": "lattiero_caseario",
        "sector_slug": "lattiero-caseario",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione e trasformazione di latte, latticini e prodotti derivati",
    },
    {
        "sector_name": "Carne",
        "sector_name_simple": "Carne",
        "sector_name_normalize": "carne",
        "sector_slug": "carne",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Lavorazione e trasformazione di carne e prodotti avicoli",
    },
    {
        "sector_name": "Ittico",
        "sector_name_simple": "Ittico",
        "sector_name_normalize": "ittico",
        "sector_slug": "ittico",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Lavorazione e trasformazione di pesce, molluschi e altri prodotti ittici",
    },
    {
        "sector_name": "Ortofrutticolo",
        "sector_name_simple": "Ortofrutticolo",
        "sector_name_normalize": "ortofrutticolo",
        "sector_slug": "ortofrutticolo",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Lavorazione, conservazione e trasformazione di frutta e verdura",
    },
    {
        "sector_name": "Cerealicolo",
        "sector_name_simple": "Cerealicolo",
        "sector_name_normalize": "cerealicolo",
        "sector_slug": "cerealicolo",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Lavorazione dei cereali, molitura e produzione di farine e semole",
    },
    {
        "sector_name": "Panificazione",
        "sector_name_simple": "Panificazione",
        "sector_name_normalize": "panificazione",
        "sector_slug": "panificazione",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione di pane, prodotti da forno e prodotti da pasticceria",
    },
    {
        "sector_name": "Dolciario",
        "sector_name_simple": "Dolciario",
        "sector_name_normalize": "dolciario",
        "sector_slug": "dolciario",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione di caramelle, cioccolato e altri prodotti dolciari",
    },
    {
        "sector_name": "Piatti pronti",
        "sector_name_simple": "Piatti pronti",
        "sector_name_normalize": "piatti_pronti",
        "sector_slug": "piatti-pronti",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione di piatti pronti, pasti confezionati e alimenti preparati",
    },
    {
        "sector_name": "Oli e grassi",
        "sector_name_simple": "Oli e grassi",
        "sector_name_normalize": "oli_e_grassi",
        "sector_slug": "oli-grassi",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione e trasformazione di oli e grassi destinati all'alimentazione",
    },
    {
        "sector_name": "Ovoprodotti",
        "sector_name_simple": "Ovoprodotti",
        "sector_name_normalize": "ovoprodotti",
        "sector_slug": "ovoprodotti",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Lavorazione, trasformazione e confezionamento di uova e ovoprodotti",
    },
    {
        "sector_name": "Bevande",
        "sector_name_simple": "Bevande",
        "sector_name_normalize": "bevande",
        "sector_slug": "bevande",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione e trasformazione di bevande alimentari",
    },
    {
        "sector_name": "Birrario",
        "sector_name_simple": "Birrario",
        "sector_name_normalize": "birrario",
        "sector_slug": "birrario",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione e lavorazione della birra",
    },
    {
        "sector_name": "Vitivinicolo",
        "sector_name_simple": "Vitivinicolo",
        "sector_name_normalize": "vitivinicolo",
        "sector_slug": "vitivinicolo",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione, lavorazione e conservazione del vino",
    },
    {
        "sector_name": "Distillati",
        "sector_name_simple": "Distillati",
        "sector_name_normalize": "distillati",
        "sector_slug": "distillati",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione di distillati e altre bevande alcoliche ottenute per distillazione",
    },
    {
        "sector_name": "Bevande analcoliche",
        "sector_name_simple": "Bevande analcoliche",
        "sector_name_normalize": "bevande_analcoliche",
        "sector_slug": "bevande-analcoliche",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione di succhi di frutta, bibite e altre bevande analcoliche",
    },
    {
        "sector_name": "Acque",
        "sector_name_simple": "Acque",
        "sector_name_normalize": "acque",
        "sector_slug": "acque",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Imbottigliamento e confezionamento di acqua potabile e acque minerali",
    },
    {
        "sector_name": "Logistica alimentare",
        "sector_name_simple": "Logistica alimentare",
        "sector_name_normalize": "logistica_alimentare",
        "sector_slug": "logistica-alimentare",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Stoccaggio, movimentazione e distribuzione di prodotti alimentari",
    },
    {
        "sector_name": "Catena del freddo",
        "sector_name_simple": "Catena del freddo",
        "sector_name_normalize": "catena_del_freddo",
        "sector_slug": "catena-del-freddo",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Conservazione e stoccaggio refrigerato o surgelato di prodotti alimentari",
    },
    {
        "sector_name": "Ingredientistica",
        "sector_name_simple": "Ingredientistica",
        "sector_name_normalize": "ingredientistica",
        "sector_slug": "ingredientistica",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione e lavorazione di ingredienti destinati all'industria alimentare",
    },
    {
        "sector_name": "Packaging alimentare",
        "sector_name_simple": "Packaging alimentare",
        "sector_name_normalize": "packaging_alimentare",
        "sector_slug": "packaging-alimentare",
        "sector_parent_name_normalize": "alimentare_e_bevande",
        "description": "Produzione e utilizzo di imballaggi e confezioni per prodotti alimentari",
    },

]
